// These contain the dummy data for the task, as no real API access is given.
// **Do not edit this file.**

import 'package:dine_out_client/model/placeholder_models.dart';

const Category startersA = Category(
    "a",
    "Starters",
    [
      Entry("a", "Salad", "A fresh salad", false, true, false, [5.0]),
      Entry("b", "Soup", "A warm soup", true, false, false, [4.0]),
      Entry("c", "Bread", "A piece of bread", false, false, false, [2.0])
    ],
    null);

const Category mainDishesA = Category(
    "b",
    "Main Dishes",
    [
      Entry("d", "Pasta", "Pasta with tomato sauce", true, false, false, [8.0]),
      Entry("e", "Pizza", "Pizza with cheese", false, true, false, [10.0]),
      Entry("f", "Burger", "A burger with fries", false, false, false, [9.0])
    ],
    null);

const Category childDishesA = Category(
    "1",
    "For children",
    [
      Entry("g", "Spaghetti", "Spaghetti with tomato sauce", true, false, true, [6.0]),
      Entry("h", "Fries", "Fries with ketchup", false, false, true, [4.0]),
      Entry("i", "Pancakes", "Pancakes with syrup", false, false, true, [5.0])
    ],
    mainDishesA);

const Category dessertsA = Category(
    "c",
    "Desserts",
    [
      Entry("j", "Ice cream", "Vanilla ice cream", false, true, false, [3.0]),
      Entry("k", "Cake", "A piece of cake", false, true, false, [4.0]),
      Entry("l", "Pudding", "A cup of pudding", false, true, false, [3.0])
    ],
    null);

const Category drinksA = Category("d", "Drinks", [], null);

const Category coldDrinksA = Category(
    "e",
    "Soft Drinks",
    [
      Entry("n", "Water", "A bottle of water", true, true, false, [2.0]),
      Entry("o", "Cola", "A glass of cola", true, true, false, [3.0]),
      Entry("p", "Orange Juice", "A glass of orange juice", true, true, false, [3.0])
    ],
    drinksA);

const Category hotDrinksA = Category(
    "f",
    "Hot Drinks",
    [
      Entry("q", "Coffee", "A cup of coffee", true, true, false, [3.0]),
      Entry("r", "Tea", "A cup of tea", true, true, false, [3.0]),
      Entry("s", "Hot Chocolate", "A cup of hot chocolate", true, true, false, [3.0])
    ],
    drinksA);

const Category alcoholicDrinksA = Category(
    "g",
    "Alcoholic Drinks",
    [
      Entry("t", "Beer", "A glass of beer", true, true, false, [4.0]),
      Entry("u", "Wine", "A glass of wine", true, true, false, [5.0]),
      Entry("v", "Cocktail", "A cocktail", true, true, false, [6.0])
    ],
    coldDrinksA);

const Category expensiveDrinksA = Category(
    "h",
    "Expensive Drinks",
    [
      Entry("w", "Champagne", "A glass of champagne", true, true, false, [10.0]),
      Entry("x", "Whiskey", "A glass of whiskey", true, true, false, [12.0]),
      Entry("y", "Vodka", "A glass of vodka", true, true, false, [11.0])
    ],
    alcoholicDrinksA);

const Category refreshments = Category(
    "z",
    "Refreshments",
    [
      Entry("z", "Ice", "This is not ice cream, just a good ol' block of pure ice", true, true, false, [100.0])
    ],
    null);

const Map<String, Restaurant> restaurants = {
  'a': Restaurant(
      "a",
      "Restaurant A",
      "A restaurant with a lot of food",
      Address("a", "Street A", "12345", "Locality A", "Comment A"),
      (53.1, 8.8),
      "https://youtu.be/dQw4w9WgXcQ",
      Menu("a", [
        startersA,
        mainDishesA,
        childDishesA,
        dessertsA,
        drinksA,
        coldDrinksA,
        hotDrinksA,
        alcoholicDrinksA,
        expensiveDrinksA
      ])),
  'b': Restaurant("b", "Restaurant B", "Not a lot going on here", Address("b", "Street B", "54321", null, null), (0, 0),
      null, Menu("b", [])),
  'c': Restaurant("c", "Restaurant C", "It's cold here", Address("b", "North Pole", "99705", "Arctic", "Igloo 1"),
      (90, 0), null, Menu("c", [refreshments])),
};
